import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import { WalletConnectProvider } from "@/components/WalletConnectProvider";
import Header from "@/components/Header";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer, toast } from "react-toastify";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["200", "300", "400"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        <div suppressHydrationWarning={true}>
          <WalletConnectProvider>
            <Header />
            <ToastContainer />
            {children}
          </WalletConnectProvider>
        </div>
      </body>
    </html>
  );
}
